name: Deploy

on:
#  push:
#    branches: 
#      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: tmux kill-session ; cd /var/www/ && git clone git@github.com:RazerMoon/node-net-server-and-client.git tcp-server && cd tcp-server && git pull && yarn && yarn compile && touch .env && echo "IP_ADDRESS=${{ secrets.HOST }}" >> .env && tmux new-session -s tcp-server -d && tmux send -t tcp-server yarn SPACE server ENTER